thresholds:
  bootstrap_threshold: 0
  rf_threshold: 100
params:
  data_type: dna
  step_size: 1
  window_size: 9
  strategy: fasttree
  geo_file: config/geo_leopard.csv
  seq_file: config/aln_leopard.fa
  specimen_id: id
  feature_names:
    - DEC-FEB
    - MAR-MAY
    - JUN-AUG
    - SEP-NOV
