thresholds:
  bootstrap_threshold: 0
  rf_threshold: 100
params:
  data_type: dna
  step_size: 1
  window_size: 9
  strategy: fasttree
  geo_file: config/geo_hornet.csv
  seq_file: config/aln_hornet.fa
  specimen_id: sequence_ID
  feature_names:
    - PRECTOTCORR_SUM
    - QV2M
    - RH2M
    - WD10M
    - WS10M
