---
Thresholds:
  bootstrap_threshold: 0
  rf_threshold: 99
params:
  data_type: aa
  geo_file: data/geo_p.csv
  seq_file: data/align_p.fa
  specimen_id: id
  step_size: 200
  window_size: 100
  strategy: raxml