---
Thresholds:
  bootstrap_threshold: 0
  rf_threshold: 99
params:
  data_type: aa
  geo_file: config/geo.csv
  seq_file: config/align.fa
  specimen_id: id
  step_size: 200
  window_size: 100
  strategy: fasttree