thresholds:
  bootstrap_threshold: 0
  rf_threshold: 100
params:
  data_type: dna
  step_size: 20
  window_size: 20
  strategy: fasttree
  geo_file: config/sample_geo.csv
  seq_file: config/sample_seq.fa
  specimen_id: id
  feature_names:
    - T2M
